spring:
  cloud:
    nacos:
      discovery:
        metadata:
          context-path: ${spring.application.name}
          #context-path: ${server.servlet.context-path}
---
spring:
  config:
    activate:
      on-profile: dev
  # 服务发现
  cloud:
    nacos:
      discovery:
        server-addr: app-server.luopc.com:7072,data-server.luopc.com:7072,core-server.luopc.com:7072
        namespace: bc6fe7b7-fbaa-4471-8a9c-d7786793a42f
        register:
          group-name: DEFAULT_GROUP
      config:
        server-addr: app-server.luopc.com:7072,data-server.luopc.com:7072,core-server.luopc.com:7072
        namespace: bc6fe7b7-fbaa-4471-8a9c-d7786793a42f
        group: DEFAULT_GROUP

---
spring:
  config:
    activate:
      on-profile: uat
  # 服务发现
  cloud:
    nacos:
      discovery:
        server-addr: app-server.luopc.com:7072,data-server.luopc.com:7072,core-server.luopc.com:7072
        namespace: 8f1da063-61b2-4567-b4cf-037aa34d66e5
        register:
          group-name: DEFAULT_GROUP
      config:
        server-addr: app-server.luopc.com:7072,data-server.luopc.com:7072,core-server.luopc.com:7072
        namespace: 8f1da063-61b2-4567-b4cf-037aa34d66e5
        group: DEFAULT_GROUP
